version: 2
jobs:
  build:
    docker:
      — image: circleci/node:10.16.0-stretch
    working_directory: ~/repo
    steps:
      — checkout
    - run:
        name: Install all packages-npm
        command: 'npm install'
 
    - run:
        name: Run tests and generate coverage
        command: 'npm test'
 